name = "MaskRCNN"
uuid = "ec2333e4-e848-462f-a4e8-9e26df145cae"
authors = ["Christian Donnerer <christian.donnerer@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
